/**
 * Vendored lexicon access. Regenerated by the vendor step of the weekly
 * sync whenever lexicons/ changes — imports are explicit so bundlers
 * carry the documents without filesystem access at runtime.
 */

import space_applyWrites from "../lexicons/space/applyWrites.json" with { type: "json" };
import space_createRecord from "../lexicons/space/createRecord.json" with { type: "json" };
import space_defs from "../lexicons/space/defs.json" with { type: "json" };
import space_deleteRecord from "../lexicons/space/deleteRecord.json" with { type: "json" };
import space_getBlob from "../lexicons/space/getBlob.json" with { type: "json" };
import space_getDelegationToken from "../lexicons/space/getDelegationToken.json" with { type: "json" };
import space_getLatestCommit from "../lexicons/space/getLatestCommit.json" with { type: "json" };
import space_getRecord from "../lexicons/space/getRecord.json" with { type: "json" };
import space_getRepo from "../lexicons/space/getRepo.json" with { type: "json" };
import space_getSpaceCredential from "../lexicons/space/getSpaceCredential.json" with { type: "json" };
import space_listBlobs from "../lexicons/space/listBlobs.json" with { type: "json" };
import space_listRecords from "../lexicons/space/listRecords.json" with { type: "json" };
import space_listRepoOps from "../lexicons/space/listRepoOps.json" with { type: "json" };
import space_listRepos from "../lexicons/space/listRepos.json" with { type: "json" };
import space_listSpaces from "../lexicons/space/listSpaces.json" with { type: "json" };
import space_notifySpaceDeleted from "../lexicons/space/notifySpaceDeleted.json" with { type: "json" };
import space_notifyWrite from "../lexicons/space/notifyWrite.json" with { type: "json" };
import space_putRecord from "../lexicons/space/putRecord.json" with { type: "json" };
import space_registerNotify from "../lexicons/space/registerNotify.json" with { type: "json" };
import space_unregisterNotify from "../lexicons/space/unregisterNotify.json" with { type: "json" };
import simplespace_addMember from "../lexicons/simplespace/addMember.json" with { type: "json" };
import simplespace_checkUserAccess from "../lexicons/simplespace/checkUserAccess.json" with { type: "json" };
import simplespace_createSpace from "../lexicons/simplespace/createSpace.json" with { type: "json" };
import simplespace_defs from "../lexicons/simplespace/defs.json" with { type: "json" };
import simplespace_deleteSpace from "../lexicons/simplespace/deleteSpace.json" with { type: "json" };
import simplespace_getSpace from "../lexicons/simplespace/getSpace.json" with { type: "json" };
import simplespace_listMembers from "../lexicons/simplespace/listMembers.json" with { type: "json" };
import simplespace_removeMember from "../lexicons/simplespace/removeMember.json" with { type: "json" };
import simplespace_updateSpace from "../lexicons/simplespace/updateSpace.json" with { type: "json" };

export interface LexiconDoc {
	lexicon: number;
	id: string;
	defs: Record<string, unknown>;
}

export const lexicons: LexiconDoc[] = [
	space_applyWrites as LexiconDoc,
	space_createRecord as LexiconDoc,
	space_defs as LexiconDoc,
	space_deleteRecord as LexiconDoc,
	space_getBlob as LexiconDoc,
	space_getDelegationToken as LexiconDoc,
	space_getLatestCommit as LexiconDoc,
	space_getRecord as LexiconDoc,
	space_getRepo as LexiconDoc,
	space_getSpaceCredential as LexiconDoc,
	space_listBlobs as LexiconDoc,
	space_listRecords as LexiconDoc,
	space_listRepoOps as LexiconDoc,
	space_listRepos as LexiconDoc,
	space_listSpaces as LexiconDoc,
	space_notifySpaceDeleted as LexiconDoc,
	space_notifyWrite as LexiconDoc,
	space_putRecord as LexiconDoc,
	space_registerNotify as LexiconDoc,
	space_unregisterNotify as LexiconDoc,
	simplespace_addMember as LexiconDoc,
	simplespace_checkUserAccess as LexiconDoc,
	simplespace_createSpace as LexiconDoc,
	simplespace_defs as LexiconDoc,
	simplespace_deleteSpace as LexiconDoc,
	simplespace_getSpace as LexiconDoc,
	simplespace_listMembers as LexiconDoc,
	simplespace_removeMember as LexiconDoc,
	simplespace_updateSpace as LexiconDoc,
];
