import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const DEV_VARS_PATH = resolve(process.cwd(), ".dev.vars");

export function readDevVars(): Record<string, string> {
	if (!existsSync(DEV_VARS_PATH)) {
		return {};
	}

	const content = readFileSync(DEV_VARS_PATH, "utf-8");
	const vars: Record<string, string> = {};

	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (trimmed && !trimmed.startsWith("#")) {
			const eqIndex = trimmed.indexOf("=");
			if (eqIndex > 0) {
				const key = trimmed.slice(0, eqIndex);
				const value = trimmed.slice(eqIndex + 1);
				vars[key] = value;
			}
		}
	}

	return vars;
}

export function writeDevVars(vars: Record<string, string>): void {
	const existing = readDevVars();
	const merged = { ...existing, ...vars };

	const lines = [
		"# Development secrets for local dev environment",
		"# Generated by: pds init",
		"",
	];

	for (const [key, value] of Object.entries(merged)) {
		lines.push(`${key}=${value}`);
	}

	writeFileSync(DEV_VARS_PATH, lines.join("\n") + "\n");
}

export function appendDevVar(key: string, value: string): void {
	writeDevVars({ [key]: value });
}

export function appendDevVars(vars: Record<string, string>): void {
	writeDevVars(vars);
}
